[build]
  command = "yarn export"
  publish = "out"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[[redirects]]
  from = "/feed"
  to = "/feed.xml"

[[redirects]]
  from = "/rss"
  to = "/feed.xml"

# 💩💩💩

[[redirects]]
  from = "/admin"
  to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

[[redirects]]
  from = "/wp-admin"
  to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

[[redirects]]
  from = "/wp-admin.php"
  to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
