name: Validate Project

on: [push]

jobs:
  validate-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
      - name: Install dependencies
        run: yarn --non-interactive --silent
      - name: Validate project
        run: yarn validate-project
